stop if the input file does not exist

diff --git a/modules/jtframe/bin/jtsim b/modules/jtframe/bin/jtsim
--- a/modules/jtframe/bin/jtsim
+++ b/modules/jtframe/bin/jtsim
@@ -372,7 +372,11 @@ case "$1" in
     -inputs)
         if [[ $2 != -* ]]; then
             shift
-            cp $1 sim_inputs.hex
+            if [ ! -e "$1" ]; then
+                echo "Error: cannot find input file $1"
+                exit 1
+            fi
+            cp "$1" sim_inputs.hex
         elif [ ! -e sim_inputs.hex ]; then
             echo "-inputs specified but there is no sim_inputs.hex file"
             exit 1
